### PR TITLE
Add bubble sort on python

### PR DESCRIPTION
**Pull request by Matrix278**
Added bubble sort on python with user input

Issue #1

### CODE REVIEW

**Comment by tausiq2003** [comment]
please share the screen shot of output

**Comment by Matrix278** [comment]
@tausiq2003 
image

**Comment by Matrix278** [comment]
By the way I see that your repository is not participating in hacktoberfest, could you add `hacktoberfest` label to your repo if you are?

**Comment by Matrix278** [comment]
@tausiq2003 Could you please add the `hacktoberfest-accepted` label then?

**Pull request merged**
